name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "adv-react-application-actions"
  EB_APPLICATION_NAME      : "MyReactNewsD"
  EB_ENVIRONMENT_NAME      : "MyReactNewsD-env"
  DEPLOY_PACKAGE_NAME      : "react_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-east-2"

on: 
  push:
    branches:
      - main
      
jobs: 
  ci_cd_pipeline:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: "20.19.5"

      - name: Install dependencies
        run : npm ci

      # - name: Run Eslint
      #   run : npm run lint
      #   continue-on-error: false

      # - name: Run tests
      #   run: npm test -- --watchAll=false

      - name: Build React app
        run : npm run build

      - name: Package build for deployment 
        run : |
          zip -r ${{ env.DEPLOY_PACKAGE_NAME }} server.js package.json package-lock.json dist -x '*.git*'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region            : ${{ env.AWS_REGION_NAME }}
      
      - name: Upload package to S3
        run : |
          aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

      - name: Create new Elastic Beanstalk application version
        run: |
          echo "Waiting for Elastic Beanstalk environment '${{ env.EB_ENVIRONMENT_NAME }}' to become ready..."
          
          aws elasticbeanstalk wait environment-exists \
            --environment-names "${{ env.EB_ENVIRONMENT_NAME }}"

          aws elasticbeanstalk wait environment-health-ok \
            --environment-names "${{ env.EB_ENVIRONMENT_NAME }}"

          echo "Environment is ready. Creating new application version..."

          aws elasticbeanstalk create-application-version \
            --application-name "${{ env.EB_APPLICATION_NAME }}" \
            --version-label "${{ github.sha }}" \
            --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Deploy new version to Elastic Beanstalk
        run: |
          echo "Deploying version '${{ github.sha }}' to environment '${{ env.EB_ENVIRONMENT_NAME }}'..."
          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.EB_ENVIRONMENT_NAME }}" \
            --version-label "${{ github.sha }}"

          echo "Waiting for deployment to complete..."
          aws elasticbeanstalk wait environment-updated \
            --environment-names "${{ env.EB_ENVIRONMENT_NAME }}"

          echo "âœ… Deployment complete!"
